name: Auto-Label PRs

on:
  pull_request:
    types: [opened, edited]
permissions:
  pull-requests: write
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      #- name: Checkout repository
        #uses: actions/checkout@v3

      - name: Assign labels based on PR content
        uses: serubin/labeler@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
